### ISSUE TITLE
Coordinates don't change as you move

### ISSUE THREAD

**Issue by Super-Fluid** [Montaron/Slitherio-Plugin#3]
The coordinates also start at (0,0) the first time.

I'm using chrome on mac os x mavericks.

**Comment by ghost** [comment]
DanyBv wrote a patch a couple of days ago that I merged now. It should fix some issues, I'll test it asap.
Sorry about the slow merge, I am moving to another city these days, so my online-time is kind of sporadic :).

**Comment by ghost** [comment]
I did a minor change to DanyBvs fix and testet it, it seems to work again now.

**Comment by ghost** [comment]
Ran for a month without reappearing, closing issue.
